[rule_1]
# 规则名称
name = 库存新增
monitor_status = 2  # 精细监控
# 触发条件：quantity从0增加（核心判断字段）
# 告警描述
description = 商品库存从0变为非0，可能是新品入库
webhook = https://oapi.dingtalk.com/robot/send?access_token=3f7ca6b2d705a4867e50178cb6b2af2395dc1c6ff0f996997a424b291a54a208
[rule_1|condition_1]
target_field = quantity
condition_type = increase
old_value = 0
compare_value=100
[rule_1|condition_2]
# 触发条件：status从0变为3或4
target_field = status
condition_type = change_from_to
# 变化前的值
old_value = 0
# 变化后允许的值（逗号分隔的列表）
new_value = 3,4

[rule_2]
# 规则名称
name = 订单状态异常告警
monitor_status = 0  # 粗略监控
# 触发条件：status从0变为3或4
target_field = status
condition_type = change_from_to
# 变化前的值
old_value = 0
# 变化后允许的值（逗号分隔的列表）
new_value = 3,4
# 告警描述
description = 订单状态从初始值(0)变为异常状态(3/4)，需人工核查
webhook = https://